Document: libbpf
Title: Debian libbpf Manual
Author: <insert document author here>
Abstract: This manual describes what libbpf is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libbpf/libbpf.sgml.gz

Format: postscript
Files: /usr/share/doc/libbpf/libbpf.ps.gz

Format: text
Files: /usr/share/doc/libbpf/libbpf.text.gz

Format: HTML
Index: /usr/share/doc/libbpf/html/index.html
Files: /usr/share/doc/libbpf/html/*.html
